nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: This is api BileMo
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/products(?!/doc$)
            - ^/api/users(?!/doc$)
