# This is a basic workflow that is manually triggered
name: Continious Integration

on: push
stages:
  -test

variables:
  APP_ENV: test

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
        - run: apt-get update -ypq
        - run: apt-get install zip unzip
        - run: apt-get install wget -yqq
        - run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - run: php composer-setup.php
        - run: php -r "unlink('composer-setup.php');"
        - run: wget https://get.symfony.com/cli/installer -O - | bash
        - run: mv /root/.symfony/bin/symfony /usr/local/bin/symfony
        - run: symfony composer install
        - run: symfony console doctrine:database:create --env=test
        - run: symfony console doctrine:migrations:migrate --force --env=test
        - run: symfony console doctrine:fixtures:load --force --env=test
        - run: symfony run bin/phpunit
        - run: echo "test complete"

