# This is a basic workflow that is manually triggered
name: Continious Integration
image: php:7.2.5-cli

cache:
  paths:
    - vendor/

stages:
  -test

variables:
  APP_ENV: test

test:
  stage: test

  before_script:
    - apt-get update -ypq
    - apt-get install zip unzip
    - apt-get install wget -yqq
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - wget https://get.symfony.com/cli/installer -O - | bash
    - mv /root/.symfony/bin/symfony /usr/local/bin/symfony

  script:
    - symfony composer install
    - symfony console doctrine:database:create --env=test
    - symfony console doctrine:migrations:migrate --force --env=test
    - symfony console doctrine:fixtures:load --force --env=test
    - symfony run bin/phpunit
    - echo "test complete"

